kind: Deployment
apiVersion: apps/v1
metadata:
  name: stablecog-deployment
  namespace: stablecog
  labels:
    app: stablecog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stablecog
  template:
    metadata:
      labels:
        app: stablecog
    spec:
      containers:
        - name: stablecog
          image: replaceme
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 200Mi
          ports:
            - containerPort: 3000
          imagePullPolicy: 'Always'
          envFrom:
            - secretRef:
                name: stablecog-secrets
      imagePullSecrets:
        - name: regcred
